### PR TITLE
change model_reaction structure to use stoichiometry format for …

### PR DESCRIPTION
**Pull request by mmundy42**
definition which was requested in ModelSEED/ModelSEEDDatabase#5

### CODE REVIEW

**Comment by nconrad** [comment]
Something I forgot to point out... do we really need    "PATRICSOLR:224308.49||/features/id/fig|224308.49.peg.2706" for genes, or can it just be "fig|224308.49.peg.2706"?

**Comment by samseaver** [comment]
I don't necessarily have a problem with this, but it does mean that, in order to retrieve the original feature sub-object, the path would have to be re-built independently using the genome id and feature id and code that relies on using this path would break in the meantime.

**Comment by nconrad** [comment]
oh I was talking purely about get_models.  But now I wonder when one model would have references to features in different genomes.  Community modeling?

**Comment by mmundy42** [comment]
The list of genes in a reaction is just what is returned by the featureUUIDs() method on a ModelReaction object.  I agree with Sam that changing that would be an incompatible change that would break other code.

Although the feature IDs in the "genes" array returned by get_model() do not have the reference prefix and it would be good for the IDs to be in the same format.

@cshenry, do the feature IDs need to have the reference prefix for community modeling?  If so, the feature IDs in the "genes" array should have the prefix too.

**Comment by mmundy42** [comment]
I merged this so as to not get behind on pull requests.  We can always tweak feature IDs later.

**Pull request merged**
